version: "3"
services:
  app:
    container_name: test_backend
    restart: always
    build: .
    depends_on:
      - "mongodb"
      - "minio"
      - "rabbitmq"
    volumes:
      - /Users/immentia/Desktop/backend_test:/app:ro
      - /app/node_modules
    ports:
      - "3050:8001"

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - "db-data:/data/db"
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - "5672:5672"

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    volumes:
      - ./minio/data/:/data
      - ./minio/conf/:/root/.minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minioUser
      MINIO_SECRET_KEY: 12345678
    command: server --console-address :9001 /data

volumes:
  db-data:
