version: '3'
services:
  app:
    container_name: test_backend
    restart: always
    build: .
    depends_on:
      - "mongodb"
    volumes:
      - /Users/ahmedjamshed/Desktop/QSTL/test_backend:/app:ro
      - /app/node_modules
    ports:
      - '3050:8001'

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - "db-data:/data/db"
    ports:
      - '27017:27017'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - '5672:5672'

volumes:
  db-data: